samples:
  SiStripCalMinBias_Express_Run2022G:
    db: /store/express/Run2022F/StreamExpress/ALCARECO/SiStripCalMinBias-Express-v1/000/362/154/00000/6a454507-dd81-4846-9152-c06bf7677a68.root
    era: '2022'
    type: data
  # SiStripCalMinBias_RelValZMM_14_HI_2021:
    # db: /store/relval/CMSSW_11_2_0_pre11/RelValZMM_14/ALCARECO/SiStripCalMinBias-112X_mcRun3_2021_realistic_v13-v1/00000/653b2de2-d195-401a-add8-49e92fc79f4d.root
    # era: '112X_mcRun3_2021_realistic'
    # type: mc
