samples:
  SiStripCalMinBias_Express_Run2022G:
    db: /store/express/Run2022G/StreamExpress/ALCARECO/SiStripCalMinBias-Express-v1/000/362/759/00000/9f733ca3-9ddb-42b7-ae35-26dafe25e0c6.root
    era: '2022'
    type: data
  # SiStripCalMinBias_RelValZMM_14_HI_2021:
    # db: /store/relval/CMSSW_11_2_0_pre11/RelValZMM_14/ALCARECO/SiStripCalMinBias-112X_mcRun3_2021_realistic_v13-v1/00000/653b2de2-d195-401a-add8-49e92fc79f4d.root
    # era: '112X_mcRun3_2021_realistic'
    # type: mc
